"""Fix primary keys again again

Revision ID: 8a20876ce11f
Revises: 614cc2f5eba9
Create Date: 2025-06-20 16:47:31.109950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a20876ce11f'
down_revision: Union[str, Sequence[str], None] = '614cc2f5eba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('book_genre_association_genre_id_fkey'), 'book_genre_association', type_='foreignkey')
    op.create_foreign_key(None, 'book_genre_association', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_genre_association', type_='foreignkey')
    op.create_foreign_key(op.f('book_genre_association_genre_id_fkey'), 'book_genre_association', 'authors', ['genre_id'], ['id'])
    # ### end Alembic commands ###
