"""Fix primary keys

Revision ID: d5696601d1bd
Revises: 12b95f224a55
Create Date: 2025-06-20 16:43:33.448396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5696601d1bd'
down_revision: Union[str, Sequence[str], None] = '12b95f224a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_genre_association', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('book_genre_association', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_genre_association', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('book_genre_association', 'book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
